import Header from "../components/Header/Header";
import '../globals.css'
import Footer from "../components/Footer/Footer";
import { ToastContainer } from 'react-toastify';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
      <Header/>
      {children}
      <Footer/>
      <ToastContainer />
      </body>
    </html>
  )
}
